# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c62795321d3714bcae17347b6777e8f5e3875efc4b058fc6df889a860583b9e7261fc84717e2912aed2372c47162d907795f36e55aed7fee7e6e01a5556c0663

test:
  secret_key_base: 4967ca86db029399deedb4d492cf7b726aaf4e522025cdc331b62175800cfce4b63105a26d58cf648a0bf6c679f7e6dc1f10bc4a5f35b15c6cc8172533c80afb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
